[package]
name = "find_prompt_instruction"
version = "0.1.0"
edition = "2021"

[dependencies]
substring_marker_snippet_extractor = { path = "../substring_marker_snippet_extractor" }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
filetime = { workspace = true }

