[package]
name = "find_prompt_instruction"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = { workspace = true }
log = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
filetime = { workspace = true }

