[package]
name = "find_referencing_files"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
