[package]
name = "prompt_file_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
