[package]
name = "prompt_file_processor"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
lazy_static = "1.4"
anyhow = "1.0"

[dev-dependencies]
tempfile = { workspace = true }
