[package]
name = "find_definition_files"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
walkdir = { workspace = true }
get_search_roots = { path = "../get_search_roots" }

[dev-dependencies]
tempfile = { workspace = true }
