[package]
name = "extract_enclosing_type"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-swift = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
