[package]
name = "extract_enclosing_type"
version = "0.1.0"
edition = "2021"

[dependencies]
todo_marker = { path = "../todo_marker" }
regex = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-swift = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
