[package]
name = "extract_instruction_content"
version = "0.1.0"
edition = "2021"

[dependencies]
todo_marker = { path = "../todo_marker" }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
