[package]
name = "extract_instruction_content"
version = "0.1.0"
edition = "2021"

[dependencies]
substring_marker_snippet_extractor = { path = "../substring_marker_snippet_extractor" }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
